---
title: "p8105_hw2_xz3312"
author: "Eric Zhang"
date: "2025-09-26"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```
#Problem 1
##Let's import the dataset pols_month and make changes to it [problem 1 part 1]
```{r}
pols_month_df = 
  read.csv("fivethirtyeight_datasets/pols-month.csv", na=c("NA",".",""))

library(dplyr)
library(tidyr)

pols_month_clean_df = 
  read.csv("fivethirtyeight_datasets/pols-month.csv", na=c("NA",".","")) %>% 
  as_tibble() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% 
  mutate(
    month = factor(month.name[month], levels = month.name),
    president = if_else(prez_gop == 1, "gop", "dem")
  ) %>% 
  select(-prez_dem, -prez_gop)
```

##Let's import the dataset snp.csv and make similar changes to it [problem 1 part 2]
```{r}
snp_df =
  read.csv("fivethirtyeight_datasets/snp.csv", na=c("NA",".",""))

library(dplyr)
library(tidyr)

snp_clean_df =
    read.csv("fivethirtyeight_datasets/snp.csv", na=c("NA",".","")) %>%
  as_tibble() %>% 
  separate(date, into = c("month","day","year"), sep = "/", convert = TRUE) %>% 
  mutate(
    year = year + if_else(year>=50L, 1900L,2000L),
    month = factor(month.name[month], levels = month.name)
  ) %>% 
  relocate(year, month, day)
      
```

##Let's import and tidy the unemployment dataset so it can be merged with previous datasets [problem 1 part 3]
```{r}
unemployment_df =
   read.csv("fivethirtyeight_datasets/unemployment.csv", na=c("NA",".",""))

library(dplyr)
library(tidyr)
library(janitor)
library(stringr)

unemployment_clean_df <-
  read.csv("fivethirtyeight_datasets/unemployment.csv",
           na = c("NA", ".", "")) %>%
  as_tibble() %>%
  clean_names() %>%
  pivot_longer(
    cols = jan:dec,              # after clean_names(): jan, feb, ..., dec
    names_to = "month",
    values_to = "unemployment_percentage"
  ) %>%
  mutate(
    month = factor(
      str_to_title(month),       # "jan" -> "Jan"
      levels = month.abb,        # "Jan","Feb",...,"Dec"
      ordered = TRUE
    )
  ) %>%
  arrange(year, month)

merge_df = pols_month_clean_df %>% 
  left_join(snp_clean_df, by = c("year", "month"))
  
```

